### ISSUE TITLE
Why not use singleton of the HttpClient object?

### ISSUE THREAD

**Issue by jeremy001181** [Scooletz/QueueBatch#12]
Would it have better performance by having a shared HttpClient object so that it reuses port for getting messages instead of allocate and dispose each time?

https://github.com/Scooletz/QueueBatch/blob/107e2f6447bd32203698cff9dd8a1aec7c2e0e21/src/QueueBatch/Impl/Queues/FastCloudQueue.cs#L118

**Comment by Scooletz** [comment]
This is by design. The pooling is done on the handler level, in a way similar to the [HttpClientFactory](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests). The client itself, is disposed similarly to package I mentioned.

Http handlers are cached for a specific amount of time using a concurrent friendly [cache](https://github.com/Scooletz/QueueBatch/blob/a4d8f0107ef4e91918bb5894a6a617d13e6945d8/src/QueueBatch/Impl/HttpMessageHandlerExpiringCache.cs), so the costs of creation etc should be amortized in time.

Does it answer the question? If yes, please close, if not - please provide more evidence and/or background for this issue.

**Comment by jeremy001181** [comment]
yes it does thank you
